/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfm_lp_GLPKPeer */

#ifndef _Included_jfm_lp_GLPKPeer
#define _Included_jfm_lp_GLPKPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfm_lp_GLPKPeer
 * Method:    create
 * Signature: ([D[D[D[I[D[I[I[D[I[I[[C[[C)J
 */
JNIEXPORT jlong JNICALL Java_jfm_lp_GLPKPeer_create
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jobjectArray, jobjectArray);

/*
 * Class:     jfm_lp_GLPKPeer
 * Method:    setTermOut
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jfm_lp_GLPKPeer_setTermOut
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jfm_lp_GLPKPeer
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jfm_lp_GLPKPeer_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jfm_lp_GLPKPeer
 * Method:    solveWithNewCoefficients
 * Signature: ([D[D[D[I[IJ)I
 */
JNIEXPORT jint JNICALL Java_jfm_lp_GLPKPeer_solveWithNewCoefficients
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jintArray, jlong);

/*
 * Class:     jfm_lp_GLPKPeer
 * Method:    solveWithNewProblem
 * Signature: ([D[D[D[I[D[I[I[D[I[I[[C[[CJ)I
 */
JNIEXPORT jint JNICALL Java_jfm_lp_GLPKPeer_solveWithNewProblem
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jintArray, jintArray, jobjectArray, jobjectArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
